// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ltt_231230910_de01.Models;

#nullable disable

namespace ltt_231230910_de01.Migrations
{
    [DbContext(typeof(Ltt_231230910_de01DBContext))]
    [Migration("20251024010137_v")]
    partial class v
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ltt_231230910_de01.Models.LttComputer", b =>
                {
                    b.Property<int>("lttComId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lttComId"));

                    b.Property<string>("lttComImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lttComName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("lttComPrice")
                        .HasColumnType("float");

                    b.Property<bool>("lttComStatus")
                        .HasColumnType("bit");

                    b.HasKey("lttComId");

                    b.ToTable("LttComputer");
                });
#pragma warning restore 612, 618
        }
    }
}
